const glossaryEntries = [
    {
        id: "operating_profit_margin",
        name: "Operating Profit Margin",
        details: {
        definition: "The percentage of revenue remaining after covering operating expenses.",
        importance: "Indicates the efficiency of a company in managing its core operations.",
        whatItTellsUs: "Higher margins suggest better operational efficiency and profitability.",
        },
        },
        {
        id: "non_interest_income",
        name: "Non-Interest Income",
        details: {
        definition: "Income earned by financial institutions from activities outside interest earnings.",
        importance: "Reflects diversification of income sources and reduces reliance on interest income.",
        whatItTellsUs: "Higher non-interest income can indicate robust fee-based services.",
        },
        },
        {
        id: "other_non_operating_income",
        name: "Other Non-Operating Income",
        details: {
        definition: "Income earned from non-core business activities.",
        importance: "Shows additional revenue streams outside primary operations.",
        whatItTellsUs: "Can indicate one-time gains or the ability to capitalize on non-core assets.",
        },
        },
        {
        id: "depreciation",
        name: "Depreciation",
        details: {
        definition: "The allocation of the cost of tangible assets over their useful lives.",
        importance: "Provides insight into capital expenditure and asset management.",
        whatItTellsUs: "High depreciation expenses might indicate significant investment in fixed assets.",
        },
        },
        {
        id: "depreciation_and_amortization",
        name: "Depreciation and Amortization",
        details: {
        definition: "Combined expenses of depreciating tangible assets and amortizing intangible assets.",
        importance: "Critical for understanding non-cash expenses and true profitability.",
        whatItTellsUs: "Higher values suggest significant investment in assets, both tangible and intangible.",
        },
        },
        {
        id: "income_before_tax",
        name: "Income Before Tax",
        details: {
        definition: "The earnings a company has before taxes are deducted.",
        importance: "Gives a picture of a company's profitability before government obligations.",
        whatItTellsUs: "Higher income before tax suggests strong earnings performance.",
        },
        },
        {
        id: "income_tax_expense",
        name: "Income Tax Expense",
        details: {
        definition: "Taxes a company is obligated to pay based on its taxable income.",
        importance: "Reflects the tax obligations and planning efficiency of the company.",
        whatItTellsUs: "Higher expenses might indicate higher profits or less effective tax management.",
        },
        },
        {
        id: "interest_and_debt-expense",
        name: "Interest and Debt Expense",
        details: {
        definition: "The cost incurred from borrowing money.",
        importance: "Shows the financial burden and leverage of the company.",
        whatItTellsUs: "High interest expenses might suggest heavy reliance on debt financing.",
        },
        },
        {
        id: "net_income",
        name: "Net Income",
        details: {
        definition: "The total profit of a company after all expenses, taxes, and costs are deducted.",
        importance: "Represents the bottom line profitability.",
        whatItTellsUs: "Higher net income indicates strong overall financial health.",
        },
        },
        {
        id: "ebit",
        name: "EBIT (Earnings Before Interest and Taxes)",
        details: {
        definition: "A measure of profitability that excludes interest and income tax expenses.",
        importance: "Highlights operational efficiency without considering financing structure.",
        whatItTellsUs: "Higher EBIT suggests stronger operational performance.",
        },
        },
        {
        id: "ebitda",
        name: "EBITDA (Earnings Before Interest, Taxes, Depreciation, and Amortization)",
        details: {
        definition: "A measure of profitability before accounting for financial and accounting decisions.",
        importance: "Used to compare profitability across companies and industries.",
        whatItTellsUs: "Higher EBITDA suggests strong core operational performance.",
        },
        },
        {
            id: "total_revenue",
            name: "Total Revenue",
            details: {
                definition: "The total amount of income generated by a company from its business activities before expenses.",
                importance: "Represents the top line of a company's financial performance, showing overall sales or income.",
                whatItTellsUs: "Higher total revenue indicates strong market demand and business growth.",
            },
        },
        {
            id: "cost_of_goods_and_services_sold",
            name: "Cost of Goods and Services Sold (COGS)",
            details: {
                definition: "The direct costs associated with the production of goods and services sold by a company.",
                importance: "Helps determine gross profit and assess production efficiency.",
                whatItTellsUs: "Lower COGS relative to revenue suggests better cost management and profitability.",
            },
        },
        {
            id: "gross_profit",
            name: "Gross Profit",
            details: {
                definition: "The profit a company makes after deducting the cost of goods and services sold from total revenue.",
                importance: "Shows the efficiency of a company's production and pricing strategies.",
                whatItTellsUs: "A higher gross profit suggests strong pricing power and cost efficiency.",
            },
        },
        {
            id: "research_and_development",
            name: "Research and Development (R&D)",
            details: {
                definition: "Expenses related to the development of new products, services, or processes.",
                importance: "Essential for innovation, staying competitive, and long-term business growth.",
                whatItTellsUs: "Higher R&D spending may indicate a focus on future growth and technological advancements.",
            },
        },
        {
            id: "selling_general_and_administrative",
            name: "Selling, General, and Administrative (SG&A) Expenses",
            details: {
                definition: "Operating expenses not directly tied to production, including marketing, salaries, and office costs.",
                importance: "Represents a major component of a company's cost structure.",
                whatItTellsUs: "Lower SG&A expenses relative to revenue indicate better cost control and operational efficiency.",
            },
        },
        {
            id: "investment_income_net",
            name: "Net Investment Income",
            details: {
                definition: "Income earned from investments, such as dividends, interest, and capital gains.",
                importance: "Provides additional revenue sources beyond core business operations.",
                whatItTellsUs: "Higher net investment income suggests effective asset management and diversification.",
            },
        },
        {
            id: "net_interest_income",
            name: "Net Interest Income",
            details: {
                definition: "The difference between interest earned on assets and interest paid on liabilities.",
                importance: "Crucial for banks and financial institutions as a primary source of earnings.",
                whatItTellsUs: "Higher net interest income indicates profitability from lending and investment activities.",
            },
        },
        {
            id: "other_non_operating_income",
            name: "Other Non-Operating Income",
            details: {
                definition: "Revenue from activities not related to a company’s core operations, such as asset sales.",
                importance: "Can provide a temporary boost to earnings but is not a sustainable revenue source.",
                whatItTellsUs: "Higher non-operating income may indicate reliance on one-time gains rather than core business growth.",
            },
        },
        {
            id: "income_before_tax",
            name: "Income Before Tax",
            details: {
                definition: "The company's earnings before accounting for income taxes.",
                importance: "Represents profitability before government taxation.",
                whatItTellsUs: "Higher income before tax suggests strong financial performance and revenue generation.",
            },
        },
        {
            id: "interest_expense",
            name: "Interest Expense",
            details: {
                definition: "The cost incurred by a company for borrowed funds, including loans and bonds.",
                importance: "Impacts net profitability and cash flow management.",
                whatItTellsUs: "Lower interest expenses indicate efficient debt management and lower financial risk.",
            },
        },
        {
            id: "income_tax_expense",
            name: "Income Tax Expense",
            details: {
                definition: "The amount a company owes in taxes based on its earnings before tax.",
                importance: "A significant financial obligation that affects net income.",
                whatItTellsUs: "Higher tax expenses can indicate strong profitability but may also reduce net earnings.",
            },
        },
        // Add similar structures for all other financial indicators
  ];
  
  export default glossaryEntries;
  